# Generated by Django 2.1.5 on 2021-10-31 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouppost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allposts',
            name='post_likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
