# Generated by Django 2.1.5 on 2021-10-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouppost', '0002_auto_20211031_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='allposts',
            name='post_likes_count',
            field=models.IntegerField(null=True),
        ),
    ]
